framework: mocha
tier: xlarge
postMerge:
  pattern:
    - "./test/**/*.spec.ts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm install
        - npm run tsc
postRun:
     command:
        - node --version
configFile: "./mocha-config/puppeteer-unit-tests.js"
version: 2.0
